
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/hubert/.cache/JetBrains/RemoteDev/dist/b21c2b5ff1f19_CLion-2023.2.2/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 5.10.102.1-microsoft-standard-WSL2 - x86_64
...
