name: Build and Test in Docker Container with OpenSUSE

on:
  pull_request:

jobs:
    BUILD:
        name:  Build project in Docker conatiner
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}
                submodules: recursive

            - name: Check Current Directory
              run: |
                echo "Current Directory:"
                pwd  # Print the current working directory
                echo "Contents of Current Directory:"
                ls -la  # List all files and directories in the current directory

            - name: Build Docker Image
              run: |
                docker buildx build -t custom-opensuse-image:latest -f ./DockerFiles/Dockerfile .

            - name: Build Project in Container
              run: |
                docker run custom-opensuse-image

